### ISSUE TITLE
DeepLinkDelegate not working properly 

### ISSUE THREAD

**Issue by ko7tya** [AppsFlyerSDK/AppsFlyerFramework#156]
# Report
`DeepLinkDelegate` doesn't return any information after user open app via deeplink 

## SDK Version

`6.1.4`

## What did you do?

Install via Swift Package Manager

## What did you expect to happen?

`didResolveDeepLink` should return information regarding from OneLink deeplink, after the user tap on it and the app opens

## What happened instead?

After app opens from deeplink, system event: 
`func application(_ application: UIApplication, continue userActivity: NSUserActivity, restorationHandler: @escaping ([UIUserActivityRestoring]?) -> Void) {
        AppsFlyerLib.shared().continue(userActivity, restorationHandler: nil)
}` is called and we pass data to `AppsFlyerLib` with regarding method, but we didn't receive any information from AppsFlyerLib after that

## Please provide any other relevant information.
There are 3 cases that we tested regarding OneLink deepLinks: 
1. User doesn't have installed app: 
- User taps on deeplink: 
- It sends the user to AppStore 
- User download the app and open it 
- All information regarding deeplink is coming from `func onConversionDataSuccess(_ conversionInfo: [AnyHashable: Any])`, so flow is working correctly 

2. User open app and after it taps on deeplink :
- User taps on deeplink: 
- System opens app 
- `func didResolveDeepLink(_ result: DeepLinkResult)` returns correct data

3. User has installed the app, but the app is suspended by the system: 
- User taps on deeplink: 
- System opens app 
- `func didResolveDeepLink(_ result: DeepLinkResult)` doesn't send any events

**Comment by andr-ggn** [comment]
3. 
Are you sure that you have still allocated delegate object?
`@property(weak, nonatomic) id<AppsFlyerDeepLinkDelegate> deepLinkDelegate;`
SDK does not retain your object. Maybe it released by your app?

**Comment by ko7tya** [comment]
@andr-ggn 
I checked, and delegate object not released

**Comment by tomoakley** [comment]
Hi, I believe I am also facing this issue. My app is a React Native app, so was using the AppsFlyer RN SDK, but also tried it with this SDK directly and could not resolve the OneLink.

**Comment by amit-kremer93** [comment]
@tomoakley The issue in RN SDK is fixed from version 6.2.10

**Comment by EmmaVvv** [comment]
We're also facing the same issue using IOS SDK. 
didResolveDeepLink(_ result: DeepLinkResult) not being triggered if the app is suspended by the system. 

We would highly appreciate if the issue is fixed as soon as possible

**Comment by dungntm58** [comment]
Is there any update? I'm using `6.7.0` now and still facing this issue. It only works when I paste universal links into the Chrome search bar.

**Comment by MingYik** [comment]
https://github.com/AppsFlyerSDK/AppsFlyerFramework/issues/269
